name: Deployment
# this pushes the code to the main branch
on:
  push:
    branches: [ main ]
# jobs are the steps that are executed to deploy the code
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    # steps are the tasks that are executed they can either be actions or shell commands
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v3

      - name: 'Deploy to Vercel'
        uses: amondnet/vercel-action@v19
        with:
          # vercel-token: ${{ secrets.SECRETS_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          github-token: ${{ secrets.GITHUB_TOKEN }} 